# Generated by Django 2.2.2 on 2019-06-16 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
